### ISSUE TITLE
In-game Prefab Painter

### ISSUE THREAD

**Issue by alfanzain** [AlexanderAmeye/prefab-painter#1]
Did someone know how to convert this to in-game prefab painter?
Brushing in-game, not on editor.

**Comment by MrLightful** [comment]
That is not an easy thing to do, neither a good idea. As far as I can see, the code is heavily dependent on the editor.

I mean, you surely can extract some useful logic, but it is easier to write an in-game specific script from scratch than to edit this one.

**Comment by alexanderameye** [comment]
Agree with @romatallinn here. Here is a fun post about playing prefabs in-game. https://www.reddit.com/r/Unity3D/comments/a18owb/im_playing_around_with_using_physics_for_placing/
