### ISSUE TITLE
Prefab Painter doesn't seem to work in 2019.1

### ISSUE THREAD

**Issue by alexanderameye** [AlexanderAmeye/prefab-painter#11]

**Comment by MarcusElg** [comment]
Clicking on the + button in the window does nothing in 2019.2

**Comment by joshcamas** [comment]
The + Button isn't a button, but rather a drag and drop area for you to drop prefabs into. Very awkward, but this isn't a bug.

**Comment by alexanderameye** [comment]
Yes it can be confusing. Do you have an idea to make it more clear that it's a drag/drop area?
