### ISSUE TITLE
Unity Package Manager

### ISSUE THREAD

**Issue by MeikelLP** [AlexanderAmeye/prefab-painter#6]
Hey, I'd love to use this package as dependency via Package Manager but in the current state this repository is not eligible for this.

Are there any plans on making this repository meet the unity package manager requirements?

I'd hate to include ~25MB just to use "some prefab painting tool". If I can include it as dependency I had to ad <1KB to the project and would always get the newest version.

**Comment by alexanderameye** [comment]
I modified the project so that it's just a folder with the scripts instead of a Unity project. You can now download the files somewhere, and then in your Unity project locate the package.json through the package manager to add it as a package to your project.

You can also add the package as a dependency in your project manifest file.

Let me know if this is what you wanted.

**Comment by MeikelLP** [comment]
Very nice. Theoretically it should work just fine like this.

I'm gonna test it later ~

**Comment by MeikelLP** [comment]
Ok I tested it. Installing it via dependency works just fine but I encourage you to rename your package ID from `com.ameye.prefab-painter` => `me.ameye.prefab-painter` as you are not a **com**pany ^^

And I'd love to see a clearer way to install this as a package. I think the package manager is the future of Unitys assets and that this should be the default way of installing :)

**Comment by alexanderameye** [comment]
Makes sense, I will change it to 'me'. I have never worked much with project structures like these so I'm not too familiar with naming conventions.

You mean a clearer way in general in Unity3D or for me to provide a clearer way to install it?

Asset store support for the Unity package manager is coming later this year I heard.

**Comment by MeikelLP** [comment]
Yeah like I did in [my repo](https://github.com/MeikelLP/next-haste) but you don't have to strictly copy it. Adjust it to your needs^^

Oh ok I didn't know that.
